### ISSUE TITLE
Soledad: HTTPError('422 Client Error: Unprocessable Entity',)

### ISSUE THREAD

**Issue by einyx** [leapcode/soledad#202] opened 2015-03-07 23:10 UTC
2015-03-07 20:04:42,324 - DEBUG    - L#284  : leap.keymanager:get_key() - getting key for einyx@leap.torzilla.net
2015-03-07 20:04:42,844 - ERROR    - L#622  : leap.bitmask.services.soledad.soledadbootstrapper:_gen_key() - Error while sending key!
2015-03-07 20:04:42,844 - ERROR    - L#623  : leap.bitmask.services.soledad.soledadbootstrapper:_gen_key() - 422 Client Error: Unprocessable Entity
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/services/soledad/soledadbootstrapper.py", line 620, in _gen_key
    self._keymanager.send_key(openpgp.OpenPGPKey)
  File "/usr/lib/python2.7/dist-packages/leap/keymanager/__init__.py", line 255, in send_key
    self._put(uri, data)
  File "/usr/lib/python2.7/dist-packages/leap/keymanager/__init__.py", line 189, in _put
    res.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 722, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 422 Client Error: Unprocessable Entity
2015-03-07 20:04:42,853 - ERROR    - L#674  : leap.bitmask.services.soledad.soledadbootstrapper:run_soledad_setup_checks() - Error while bootstrapping Soledad: HTTPError('422 Client Error: Unprocessable Entity',)
Traceback (most recent call last):

**Comment by kalikaneko** [comment] 2015-03-08 03:45
hi @einyx, thanks for the report
what version of soledad have you got in the server?
what version of the  client are you testing with?

**Comment by ivanalejandro0** [comment] 2015-03-16 14:31
@kalikaneko there is an issue report for this, https://leap.se/code/issues/4493

**Comment by kalikaneko** [comment] 2015-03-16 14:51
any help leading to reproduce this would be greatly welcome

**Comment by KwadroNaut** [comment] 2017-04-19 13:17
No updates since a long time, closing now.

**Closed by KwadroNaut** 2017-04-19 13:17 UTC
